# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-01-29 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='sport',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('football', 'Football'), ('baseball', 'Baseball'), ('cricket', 'Cricket'), ('hockey', 'Hockey')], default='basketball', max_length=10),
        ),
    ]
